apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-green
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kube-green/kube-green
    path: config/default
    targetRevision: '8e2ad865ceb5e7a000616f886683d71bfbdc1ec2'
  destination:
    namespace: kube-green
    name: kind-kube-green
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true