apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sleepme
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/argocd-example-apps'
    path: kube-green/manifests
    targetRevision: kube-green
  destination:
    namespace: sleepme
    name: kind-kube-green
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  # ignoreDifferences:
  #   - group: apps
  #     kind: Deployment
  #     namespace: sleepme
  #     jsonPointers:
  #     - /spec/replicas